### ISSUE TITLE
Documentation on Auth log OUT ?

### ISSUE THREAD

**Issue by chreestopher** [adamdriscoll/universal-dashboard-documentation#2]
I have been playing with this for a few days now and I must say I really like it.

I just got some basic authentication setup and i realized that I can not find any details about how to log a user out of the dashboard.

I have played around trying to redirect to the login page, and various other methods includeing trying to reset the $user variable, or return a failed authentication result, etc, to no avail.

I have also googled and made my way through several pages of irrelevant results, and gone through the examples that i can find in this repo.

I would hugely appreciate it if you could point me in the direction of a proper logout example. Or even just explain the mechanism we should be using for logout functionality and then i can figure out how to implement it on my own.

Thanks.

**Comment by adamdriscoll** [comment]
This has been implemented in future versions. There is a logout link in the top right corner.
