### ISSUE TITLE
Grid example and performance issue / alternative. 

### ISSUE THREAD

**Issue by itfranck** [adamdriscoll/universal-dashboard-documentation#3]
Hi, this link: [Grid - Custom Columns](https://adamdriscoll.gitbooks.io/powershell-universal-dashboard/content/grids.html)

contains an example with Get-Process applied to a grid. 
I found that your example has very poor performance

Attempt at resolution #1 
Using -ServerSideProcessing make the processes appears a lot faster but performances while filtering remains very slow.

Solution
While looking at Out-UDGridData, I noticed that all the properties are included (equivalent to a Format-List * ) and generated into the resulting HTML. 

Instead of your example, doing   

> Get-Process | Select Name,ID,WorkingSet,CPU | Out-UDGridData

make the grid processing and filtering very fast.

**Comment by adamdriscoll** [comment]
Thanks! I updated the documentation to reflect your change!
